apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: {{ include "python-api.name" . }} }
  template:
    metadata:
      labels: { app: {{ include "python-api.name" . }} }
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports: [{ containerPort: 8080 }]
          readinessProbe: { httpGet: { path: /sum?a=0&b=0, port: 8080 }, initialDelaySeconds: 5 }
          livenessProbe: { httpGet: { path: /sum?a=0&b=0, port: 8080 }, initialDelaySeconds: 15 } 