apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "python-api.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - http:
        paths:
          - path: /sum
            pathType: Prefix
            backend:
              service:
                name: {{ include "python-api.fullname" . }}
                port: { number: 80 }