apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-api.fullname" . }}
spec:
  type: ClusterIP
  selector: { app: {{ include "python-api.name" . }} }
  ports:
    - name: http
      port: 80
      targetPort: 8080